[package]
name = "svsm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stage2"
path = "src/stage2.rs"
test = false

[[bin]]
name = "svsm"
path = "src/svsm.rs"
test = false

[lib]
test = true
doctest = true

[dependencies]
bitflags = "2.4"
gdbstub = { version = "0.6.6", default-features = false, optional = true }
gdbstub_arch = { version = "0.2.4", optional = true }
intrusive-collections = "0.9.6"
log = { version = "0.4.17", features = ["max_level_info", "release_max_level_info"] }
packit = { git = "https://github.com/coconut-svsm/packit", version = "0.1.1" }
aes-gcm = { version = "0.10.3", default-features = false, features = ["aes", "alloc"] }
bootlib = { path = "bootlib" }
igvm_defs = { version = "0.1.3", features = ["unstable"] }
cpuarch = { path = "cpuarch" }

[target."x86_64-unknown-none".dev-dependencies]
test = { version = "0.1.0", path = "test" }

[features]
default = ["enable-stacktrace"]
default-debug = ["enable-stacktrace", "enable-console-log"]
enable-stacktrace = []
enable-gdb = ["dep:gdbstub", "dep:gdbstub_arch"]
enable-console-log = []

[dev-dependencies]
memoffset = "0.9.0"
